---
name: WWW-PastebinCom-Retrieve
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  retrieve content of pastes from
  L<http://pastebin.com>
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::PastebinCom::Retrieve:
    file: lib/WWW/PastebinCom/Retrieve.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
